//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Michsky.MUIP.CustomDropdown.DropdownEvent))]
	public class PropertyProvider_Michsky_MUIP_CustomDropdown_DropdownEvent : Unity.VisualScripting.SerializedPropertyProvider<Michsky.MUIP.CustomDropdown.DropdownEvent>
	{
	}
}
